const AcademicRanksOptions = [
  "UNIVERSITY PROFESSOR",
  "PROFESSOR VI",
  "PROFESSOR V",
  "PROFESSOR IV",
  "PROFESSOR III",
  "PROFESSOR II",
  "PROFESSOR I",
  "ASSOCIATE PROFESSOR V",
  "ASSOCIATE PROFESSOR IV",
  "ASSOCIATE PROFESSOR III",
  "ASSOCIATE PROFESSOR II",
  "ASSOCIATE PROFESSOR I",
  "ASSISTANT PROFESSOR VI",
  "ASSISTANT PROFESSOR V",
  "ASSISTANT PROFESSOR IV",
  "ASSISTANT PROFESSOR III",
  "ASSISTANT PROFESSOR II",
  "ASSISTANT PROFESSOR I",
  "INSTRUCTOR III",
  "INSTRUCTOR II",
  "INSTRUCTOR I",
];

const UnitOptions = [
  "BSED-PROFED",
  "BSED-FILIPINO",
  "BSED-ENGLISH",
  "BSED-MATH",
  "BSED-VALUES EDUCATION",
  "BSED-SOCIAL STUDIES",
  "BSED-SCIENCE",
  "BEED/BECED/BSNED",
  "BPED",
  "BTLED",
  "ILS",
  "BAPOS/SOCIAL SCIENCE",
  "BACOMM",
  "SOCIAL WORK",
  "IT",
  "BLIS",
  "BSBIO/SCIENCE",
  "BAEL/LANG&LIT",
  "BMME/MAPEH & HUMANITY",
  "HM/TM",
  "ENTREP",
];

const CollegeOption = [
  "CAS",
  "COE",
  "CME"
]



export {
  AcademicRanksOptions,
  UnitOptions,
  CollegeOption
}